# Add configuration values here, as shown below.
SENDGRID_PASSWORD: fbs1b8cw
SENDGRID_USERNAME: app32738776@heroku.com
#SECRET_KEY_BASE:     ** not sure what to put in here...*** nnn          
#MY_SUPER_SECRET_VARIABLE: secret123456
