# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d5be5cff81bad8cc581104ddb365c2dd4c655fbdc2a98ea56cf0d629acfba99c8bc71b51f505d63710338803eb379ed93ccbebff6f9f7e7ba2a0b0a5b157d8

test:
  secret_key_base: cf8e96f75a219e8867b0fa2268289385c18e3a6e70708231d8b0aa73dd370c856f82f865112224dd3793e8f4a0f311fc1b0f8015114ef061e3d31087ef039f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
